// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoElEhqn03Qpud-ybBAF2fY-ut_djDC80',
    appId: '1:607585428550:web:2eecbe09c2a973f4e01647',
    messagingSenderId: '607585428550',
    projectId: 'maenprototype',
    authDomain: 'maenprototype.firebaseapp.com',
    databaseURL: 'https://maenprototype-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maenprototype.firebasestorage.app',
    measurementId: 'G-088V3LW7KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjWTu6qrqBwYpLoTnUtlLHCbAb7T1vzxg',
    appId: '1:607585428550:android:6549e2e08b299e7de01647',
    messagingSenderId: '607585428550',
    projectId: 'maenprototype',
    databaseURL: 'https://maenprototype-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maenprototype.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJg77PqurQcBi-9dT-UplKIAWtauNhOCs',
    appId: '1:607585428550:ios:8ee8c21e9c5dfb79e01647',
    messagingSenderId: '607585428550',
    projectId: 'maenprototype',
    databaseURL: 'https://maenprototype-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maenprototype.firebasestorage.app',
    androidClientId: '607585428550-60faohkk4a2uafhdoi57tc0r9pbc1h9q.apps.googleusercontent.com',
    iosClientId: '607585428550-olg31j3j0n6oboag5n5lsuo9fh1p8q3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.kerjaPraktekTugas',
  );
}
